// <auto-generated />
namespace CH.Spartan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Edit_Device1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edit_Device1));
        
        string IMigrationMetadata.Id
        {
            get { return "201604171030222_Edit_Device1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
