// <auto-generated />
namespace CH.Spartan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditDeviceStock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditDeviceStock));
        
        string IMigrationMetadata.Id
        {
            get { return "201604210641282_EditDeviceStock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
